export interface Element {
  number: number;
  symbol: string;
  name: string;
  category: string;
  period: number;
  group: number;
  mass: number;
}

export const ELEMENTS: Element[] = [
  { number: 1,   symbol: 'H',  name: 'Устөрөгч',         category: 'nonmetal',             period: 1, group: 1,  mass: 1.008 },
  { number: 2,   symbol: 'He', name: 'Гели',              category: 'noble-gas',            period: 1, group: 18, mass: 4.003 },
  { number: 3,   symbol: 'Li', name: 'Лити',              category: 'alkali-metal',         period: 2, group: 1,  mass: 6.941 },
  { number: 4,   symbol: 'Be', name: 'Берили',            category: 'alkaline-earth',       period: 2, group: 2,  mass: 9.012 },
  { number: 5,   symbol: 'B',  name: 'Бор',               category: 'metalloid',            period: 2, group: 13, mass: 10.811 },
  { number: 6,   symbol: 'C',  name: 'Нүүрстөрөгч',      category: 'nonmetal',             period: 2, group: 14, mass: 12.011 },
  { number: 7,   symbol: 'N',  name: 'Азот',              category: 'nonmetal',             period: 2, group: 15, mass: 14.007 },
  { number: 8,   symbol: 'O',  name: 'Хүчилтөрөгч',      category: 'nonmetal',             period: 2, group: 16, mass: 15.999 },
  { number: 9,   symbol: 'F',  name: 'Фтор',              category: 'halogen',              period: 2, group: 17, mass: 18.998 },
  { number: 10,  symbol: 'Ne', name: 'Неон',              category: 'noble-gas',            period: 2, group: 18, mass: 20.180 },
  { number: 11,  symbol: 'Na', name: 'Натри',             category: 'alkali-metal',         period: 3, group: 1,  mass: 22.990 },
  { number: 12,  symbol: 'Mg', name: 'Магни',             category: 'alkaline-earth',       period: 3, group: 2,  mass: 24.305 },
  { number: 13,  symbol: 'Al', name: 'Хөнгөн цагаан',    category: 'post-transition-metal', period: 3, group: 13, mass: 26.982 },
  { number: 14,  symbol: 'Si', name: 'Цахиур',            category: 'metalloid',            period: 3, group: 14, mass: 28.086 },
  { number: 15,  symbol: 'P',  name: 'Фосфор',            category: 'nonmetal',             period: 3, group: 15, mass: 30.974 },
  { number: 16,  symbol: 'S',  name: 'Хүхэр',             category: 'nonmetal',             period: 3, group: 16, mass: 32.065 },
  { number: 17,  symbol: 'Cl', name: 'Хлор',              category: 'halogen',              period: 3, group: 17, mass: 35.453 },
  { number: 18,  symbol: 'Ar', name: 'Аргон',             category: 'noble-gas',            period: 3, group: 18, mass: 39.948 },
  { number: 19,  symbol: 'K',  name: 'Кали',              category: 'alkali-metal',         period: 4, group: 1,  mass: 39.098 },
  { number: 20,  symbol: 'Ca', name: 'Кальци',            category: 'alkaline-earth',       period: 4, group: 2,  mass: 40.078 },
  { number: 21,  symbol: 'Sc', name: 'Скандий',           category: 'transition-metal',     period: 4, group: 3,  mass: 44.956 },
  { number: 22,  symbol: 'Ti', name: 'Титан',             category: 'transition-metal',     period: 4, group: 4,  mass: 47.867 },
  { number: 23,  symbol: 'V',  name: 'Ванади',            category: 'transition-metal',     period: 4, group: 5,  mass: 50.942 },
  { number: 24,  symbol: 'Cr', name: 'Хром',              category: 'transition-metal',     period: 4, group: 6,  mass: 51.996 },
  { number: 25,  symbol: 'Mn', name: 'Манган',            category: 'transition-metal',     period: 4, group: 7,  mass: 54.938 },
  { number: 26,  symbol: 'Fe', name: 'Төмөр',             category: 'transition-metal',     period: 4, group: 8,  mass: 55.845 },
  { number: 27,  symbol: 'Co', name: 'Кобальт',           category: 'transition-metal',     period: 4, group: 9,  mass: 58.933 },
  { number: 28,  symbol: 'Ni', name: 'Никель',            category: 'transition-metal',     period: 4, group: 10, mass: 58.693 },
  { number: 29,  symbol: 'Cu', name: 'Зэс',               category: 'transition-metal',     period: 4, group: 11, mass: 63.546 },
  { number: 30,  symbol: 'Zn', name: 'Цайр',              category: 'transition-metal',     period: 4, group: 12, mass: 65.38 },
  { number: 31,  symbol: 'Ga', name: 'Гали',              category: 'post-transition-metal', period: 4, group: 13, mass: 69.723 },
  { number: 32,  symbol: 'Ge', name: 'Герман',            category: 'metalloid',            period: 4, group: 14, mass: 72.630 },
  { number: 33,  symbol: 'As', name: 'Хүнцэл',            category: 'metalloid',            period: 4, group: 15, mass: 74.922 },
  { number: 34,  symbol: 'Se', name: 'Селен',             category: 'nonmetal',             period: 4, group: 16, mass: 78.971 },
  { number: 35,  symbol: 'Br', name: 'Бром',              category: 'halogen',              period: 4, group: 17, mass: 79.904 },
  { number: 36,  symbol: 'Kr', name: 'Криптон',           category: 'noble-gas',            period: 4, group: 18, mass: 83.798 },
  { number: 37,  symbol: 'Rb', name: 'Рубиди',            category: 'alkali-metal',         period: 5, group: 1,  mass: 85.468 },
  { number: 38,  symbol: 'Sr', name: 'Стронци',           category: 'alkaline-earth',       period: 5, group: 2,  mass: 87.62 },
  { number: 39,  symbol: 'Y',  name: 'Итри',              category: 'transition-metal',     period: 5, group: 3,  mass: 88.906 },
  { number: 40,  symbol: 'Zr', name: 'Цирконий',          category: 'transition-metal',     period: 5, group: 4,  mass: 91.224 },
  { number: 41,  symbol: 'Nb', name: 'Ниоби',             category: 'transition-metal',     period: 5, group: 5,  mass: 92.906 },
  { number: 42,  symbol: 'Mo', name: 'Молибден',          category: 'transition-metal',     period: 5, group: 6,  mass: 95.96 },
  { number: 43,  symbol: 'Tc', name: 'Технеций',          category: 'transition-metal',     period: 5, group: 7,  mass: 98.0 },
  { number: 44,  symbol: 'Ru', name: 'Рутени',            category: 'transition-metal',     period: 5, group: 8,  mass: 101.07 },
  { number: 45,  symbol: 'Rh', name: 'Роди',              category: 'transition-metal',     period: 5, group: 9,  mass: 102.905 },
  { number: 46,  symbol: 'Pd', name: 'Паллади',           category: 'transition-metal',     period: 5, group: 10, mass: 106.42 },
  { number: 47,  symbol: 'Ag', name: 'Мөнгө',             category: 'transition-metal',     period: 5, group: 11, mass: 107.868 },
  { number: 48,  symbol: 'Cd', name: 'Кадми',             category: 'transition-metal',     period: 5, group: 12, mass: 112.411 },
  { number: 49,  symbol: 'In', name: 'Инди',              category: 'post-transition-metal', period: 5, group: 13, mass: 114.818 },
  { number: 50,  symbol: 'Sn', name: 'Цагаан тугалга',   category: 'post-transition-metal', period: 5, group: 14, mass: 118.710 },
  { number: 51,  symbol: 'Sb', name: 'Сурьма',            category: 'metalloid',            period: 5, group: 15, mass: 121.760 },
  { number: 52,  symbol: 'Te', name: 'Теллур',            category: 'metalloid',            period: 5, group: 16, mass: 127.60 },
  { number: 53,  symbol: 'I',  name: 'Иод',               category: 'halogen',              period: 5, group: 17, mass: 126.904 },
  { number: 54,  symbol: 'Xe', name: 'Ксенон',            category: 'noble-gas',            period: 5, group: 18, mass: 131.293 },
  { number: 55,  symbol: 'Cs', name: 'Цези',              category: 'alkali-metal',         period: 6, group: 1,  mass: 132.905 },
  { number: 56,  symbol: 'Ba', name: 'Бари',              category: 'alkaline-earth',       period: 6, group: 2,  mass: 137.327 },
  { number: 57,  symbol: 'La', name: 'Лантан',            category: 'lanthanide',           period: 6, group: 3,  mass: 138.905 },
  { number: 58,  symbol: 'Ce', name: 'Цери',              category: 'lanthanide',           period: 8, group: 4,  mass: 140.116 },
  { number: 59,  symbol: 'Pr', name: 'Празеодим',         category: 'lanthanide',           period: 8, group: 5,  mass: 140.908 },
  { number: 60,  symbol: 'Nd', name: 'Неодим',            category: 'lanthanide',           period: 8, group: 6,  mass: 144.242 },
  { number: 61,  symbol: 'Pm', name: 'Прометий',          category: 'lanthanide',           period: 8, group: 7,  mass: 145.0 },
  { number: 62,  symbol: 'Sm', name: 'Самари',            category: 'lanthanide',           period: 8, group: 8,  mass: 150.36 },
  { number: 63,  symbol: 'Eu', name: 'Европи',            category: 'lanthanide',           period: 8, group: 9,  mass: 151.964 },
  { number: 64,  symbol: 'Gd', name: 'Гадолини',          category: 'lanthanide',           period: 8, group: 10, mass: 157.25 },
  { number: 65,  symbol: 'Tb', name: 'Терби',             category: 'lanthanide',           period: 8, group: 11, mass: 158.925 },
  { number: 66,  symbol: 'Dy', name: 'Диспрози',          category: 'lanthanide',           period: 8, group: 12, mass: 162.500 },
  { number: 67,  symbol: 'Ho', name: 'Гольми',            category: 'lanthanide',           period: 8, group: 13, mass: 164.930 },
  { number: 68,  symbol: 'Er', name: 'Эрби',              category: 'lanthanide',           period: 8, group: 14, mass: 167.259 },
  { number: 69,  symbol: 'Tm', name: 'Тули',              category: 'lanthanide',           period: 8, group: 15, mass: 168.934 },
  { number: 70,  symbol: 'Yb', name: 'Иттерби',           category: 'lanthanide',           period: 8, group: 16, mass: 173.054 },
  { number: 71,  symbol: 'Lu', name: 'Лютеций',           category: 'lanthanide',           period: 8, group: 17, mass: 174.967 },
  { number: 72,  symbol: 'Hf', name: 'Гафни',             category: 'transition-metal',     period: 6, group: 4,  mass: 178.49 },
  { number: 73,  symbol: 'Ta', name: 'Тантал',            category: 'transition-metal',     period: 6, group: 5,  mass: 180.948 },
  { number: 74,  symbol: 'W',  name: 'Вольфрам',          category: 'transition-metal',     period: 6, group: 6,  mass: 183.84 },
  { number: 75,  symbol: 'Re', name: 'Рени',              category: 'transition-metal',     period: 6, group: 7,  mass: 186.207 },
  { number: 76,  symbol: 'Os', name: 'Осми',              category: 'transition-metal',     period: 6, group: 8,  mass: 190.23 },
  { number: 77,  symbol: 'Ir', name: 'Ирид',              category: 'transition-metal',     period: 6, group: 9,  mass: 192.217 },
  { number: 78,  symbol: 'Pt', name: 'Платин',            category: 'transition-metal',     period: 6, group: 10, mass: 195.084 },
  { number: 79,  symbol: 'Au', name: 'Алт',               category: 'transition-metal',     period: 6, group: 11, mass: 196.967 },
  { number: 80,  symbol: 'Hg', name: 'Мөнгөн ус',        category: 'transition-metal',     period: 6, group: 12, mass: 200.592 },
  { number: 81,  symbol: 'Tl', name: 'Тали',              category: 'post-transition-metal', period: 6, group: 13, mass: 204.383 },
  { number: 82,  symbol: 'Pb', name: 'Хар тугалга',       category: 'post-transition-metal', period: 6, group: 14, mass: 207.2 },
  { number: 83,  symbol: 'Bi', name: 'Висмут',            category: 'post-transition-metal', period: 6, group: 15, mass: 208.980 },
  { number: 84,  symbol: 'Po', name: 'Полони',            category: 'metalloid',            period: 6, group: 16, mass: 209.0 },
  { number: 85,  symbol: 'At', name: 'Астат',             category: 'halogen',              period: 6, group: 17, mass: 210.0 },
  { number: 86,  symbol: 'Rn', name: 'Радон',             category: 'noble-gas',            period: 6, group: 18, mass: 222.0 },
  { number: 87,  symbol: 'Fr', name: 'Франси',            category: 'alkali-metal',         period: 7, group: 1,  mass: 223.0 },
  { number: 88,  symbol: 'Ra', name: 'Рад',               category: 'alkaline-earth',       period: 7, group: 2,  mass: 226.0 },
  { number: 89,  symbol: 'Ac', name: 'Акти',              category: 'actinide',             period: 7, group: 3,  mass: 227.0 },
  { number: 90,  symbol: 'Th', name: 'Тори',              category: 'actinide',             period: 9, group: 4,  mass: 232.038 },
  { number: 91,  symbol: 'Pa', name: 'Протакти',          category: 'actinide',             period: 9, group: 5,  mass: 231.036 },
  { number: 92,  symbol: 'U',  name: 'Уран',              category: 'actinide',             period: 9, group: 6,  mass: 238.029 },
  { number: 93,  symbol: 'Np', name: 'Нептуни',           category: 'actinide',             period: 9, group: 7,  mass: 237.0 },
  { number: 94,  symbol: 'Pu', name: 'Плутони',           category: 'actinide',             period: 9, group: 8,  mass: 244.0 },
  { number: 95,  symbol: 'Am', name: 'Америци',           category: 'actinide',             period: 9, group: 9,  mass: 243.0 },
  { number: 96,  symbol: 'Cm', name: 'Кюри',              category: 'actinide',             period: 9, group: 10, mass: 247.0 },
  { number: 97,  symbol: 'Bk', name: 'Берклий',           category: 'actinide',             period: 9, group: 11, mass: 247.0 },
  { number: 98,  symbol: 'Cf', name: 'Калифорни',         category: 'actinide',             period: 9, group: 12, mass: 251.0 },
  { number: 99,  symbol: 'Es', name: 'Эйнштейни',         category: 'actinide',             period: 9, group: 13, mass: 252.0 },
  { number: 100, symbol: 'Fm', name: 'Ферми',             category: 'actinide',             period: 9, group: 14, mass: 257.0 },
  { number: 101, symbol: 'Md', name: 'Менделеви',         category: 'actinide',             period: 9, group: 15, mass: 258.0 },
  { number: 102, symbol: 'No', name: 'Нобели',            category: 'actinide',             period: 9, group: 16, mass: 259.0 },
  { number: 103, symbol: 'Lr', name: 'Лоуренси',          category: 'actinide',             period: 9, group: 17, mass: 266.0 },
  { number: 104, symbol: 'Rf', name: 'Резерфорди',        category: 'transition-metal',     period: 7, group: 4,  mass: 267.0 },
  { number: 105, symbol: 'Db', name: 'Дубни',             category: 'transition-metal',     period: 7, group: 5,  mass: 270.0 },
  { number: 106, symbol: 'Sg', name: 'Сиборги',           category: 'transition-metal',     period: 7, group: 6,  mass: 271.0 },
  { number: 107, symbol: 'Bh', name: 'Бори',              category: 'transition-metal',     period: 7, group: 7,  mass: 270.0 },
  { number: 108, symbol: 'Hs', name: 'Хасси',             category: 'transition-metal',     period: 7, group: 8,  mass: 277.0 },
  { number: 109, symbol: 'Mt', name: 'Мейтнери',          category: 'transition-metal',     period: 7, group: 9,  mass: 278.0 },
  { number: 110, symbol: 'Ds', name: 'Дармштадти',        category: 'transition-metal',     period: 7, group: 10, mass: 281.0 },
  { number: 111, symbol: 'Rg', name: 'Рентгени',          category: 'transition-metal',     period: 7, group: 11, mass: 282.0 },
  { number: 112, symbol: 'Cn', name: 'Коперники',         category: 'transition-metal',     period: 7, group: 12, mass: 285.0 },
  { number: 113, symbol: 'Nh', name: 'Нихони',            category: 'post-transition-metal', period: 7, group: 13, mass: 286.0 },
  { number: 114, symbol: 'Fl', name: 'Флерови',           category: 'post-transition-metal', period: 7, group: 14, mass: 289.0 },
  { number: 115, symbol: 'Mc', name: 'Московий',          category: 'post-transition-metal', period: 7, group: 15, mass: 290.0 },
  { number: 116, symbol: 'Lv', name: 'Ливерморий',        category: 'post-transition-metal', period: 7, group: 16, mass: 293.0 },
  { number: 117, symbol: 'Ts', name: 'Тенесси',           category: 'halogen',              period: 7, group: 17, mass: 294.0 },
  { number: 118, symbol: 'Og', name: 'Оганесон',          category: 'noble-gas',            period: 7, group: 18, mass: 294.0 },
];
